spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sale_master?useUnicode=true&characterEncoding=UTF-8&autocommit=false&autoReconnect=true&useSSL=false
      username: root
      password: earth&moon